name: Pipeline Health Check

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.1.0

      - name: Build Docker image
        run: docker build -t pipeline-checker .

      - name: Run pipeline health check
        run: docker run pipeline-checker