name: Pipeline Health Check

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6 AM UTC
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.1.0

      - name: Build Docker image
        run: docker build -t pipeline-checker .

      - name: Run pipeline health check
        run: docker run pipeline-checker
      - name: Copy logs from container
        run: |
          docker run --name temp_container pipeline-checker
          docker cp temp_container:/app/pipeline.log ./pipeline.log || true
          docker rm temp_container || true

      - name: Upload pipeline log
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-log
          path: pipeline.log